export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_ROBOT_PENDING = "REQUEST_ROBOT_PENDING";
export const REQUEST_ROBOT_SUCCESS = "REQUEST_ROBOT_SUCCESS";
export const REQUEST_ROBOT_FAILED = "REQUEST_ROBOT_FAILED";